CC=gcc
CFLAGS=-O2 -Wextra -Wall -D_NLINUX_
LDFLAGS=
PROG="duser"
SRC=compat.c duser.c util.c user.c log.c cfg.c
all:
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROG) $(SRC)
	strip -x $(PROG)	
clean:
	rm -rf $(PROG)
