CC=gcc
CFLAGS=-O2 -Wextra -Wall -static -D_NLINUX
LDFLAGS=
PROG="duser"
SRC=compat.c duser.c util.c user.c duser.h log.c cfg.c
all:
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROG) $(SRC)
	strip -s $(PROG)	
clean:
	rm -rf $(PROG)
